nombre = input("Ingrese su nombre: ")
apellido = input("Ingrese su apellido: ")
edad = input("Ingrese su edad: ")
residencia = input("Ingrese su lugar de residencia:")
print(f"Hola, soy ", nombre, apellido,", tengo", edad, "años y resido en ", residencia)
